OPT = -g0 -O3

LIB_SOURCES1 = test1.c
LIB_SOURCES = $(addprefix test/, $(LIB_SOURCES1))

CC = gcc
TARGET = run-test
LIB_OBJECTS =$(LIB_SOURCES:.c=.o)
LIBS= ./libmicroio.a
LDFLAGS= -L. $(OPT) -Wall -Wextra $(LIBS)

ALL= $(TARGET)
CFLAGS = -Iinclude/ -std=gnu11 -c $(OPT) -Wall  -Wextra -Werror=implicit-function-declaration -Wformat=0 -D_GNU_SOURCE -Wwrite-strings -Werror -Werror=maybe-uninitialized

ifneq ($(BUILD),release)
    CFLAGS += -DDEBUG
    OPT = -g3 -O0
endif

all: $(ALL)

libmicroio.a:
	make


$(TARGET): $(LIB_OBJECTS) libmicroio.a
	$(CC)  $(LIB_OBJECTS) $(LDFLAGS) -o $@

release debug:
	$(MAKE) BUILD=$@



.c.o: $(HEADERS) $(LEVEL_CS)
	$(CC) $(CFLAGS) $< -o $@ -MMD -MF $@.depends

depend: h-depend
clean:
	rm -f $(LIB_OBJECTS) $(ALL) src/*.o.depends src/*.o

-include $(LIB_OBJECTS:.o=.o.depends)

.PHONY: libmicroio.a $(TARGET) 

